%YAML:1.0
---
alphaForeground: 1.0000000149011612e-01
alphaBackground: 2.0000000298023224e-01
zn: 1.
zf: 4000.
histOffset: 100
histRad: 40
searchRad: 25
cameraConfigFile: "./assets/calibration_orange_A_1280_720_r.yml"
groundTruthPoses:
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
   - [ 1, 0, 0, 0,
       0, 1, 0, 0,
       0, 0, 1 ,0 ]
modelFiles:
   - "/home/as/TTool/assets/toolheads/holzkombihorer_20/model.obj"
   - "/home/as/TTool/assets/toolheads/ck30/model.obj"
   - "/home/as/TTool/assets/toolheads/drillBit_20_110/model.obj"
   - "/home/as/TTool/assets/toolheads/drillBit_14_105/model.obj"
   - "/home/as/TTool/assets/toolheads/holzspiralbohrer_sp_20/5kmodel.obj"
   - "/home/as/TTool/assets/toolheads/circular_blade_scaled/circular_blade_scaled.obj"
   - "/home/as/TTool/assets/toolheads/flachbohrer_25/flachbohrer_25.obj"
   - "/home/as/TTool/assets/toolheads/selfFeedBits_50/model.obj"
   - "/home/as/TTool/assets/toolheads/saw_blade_scaled/saw_blade_thin_verythin.obj"
   - "/home/as/TTool/assets/toolheads/forstnerbohrer_40/forstnerbohrer_40.obj"
   - "/home/as/TTool/assets/toolheads/selfFeedBits_40_90/model.obj"
frames: ""
cameraID: 0