name: CMakeBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:


    

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libopencv-dev
        version: 4.5.5

    - uses: actions/checkout@v3
      with:
          # repository: ibois-epfl/TTool
          token: ${{ secrets.ACCESS_TOKEN }}
          # submodules: recursive

    - name: submodules recursively
      run: git submodule update --init --recursive


    - name: Configure CMake
      run: ./configure.sh

    - name: Build
      run: ./build.sh