name: CMakeBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:

    


    # - uses: actions/checkout@v1
    #   with:
    #     token: ${{ secrets.ACCESS_TOKEN }}
    #     submodules: true


    - uses: actions/checkout@v3

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libopencv-dev
        version: 4.5.5


    - name: clone submodule
      uses: actions/checkout@v2
      with:
        repository: <org name>/<repo name>
        path: path
        ssh-key: ${{ secrets.SSH_KEY }}
        persist-credentials: true

    - name: checkout submodule
      run: |
        git submodule init
        git submodule update




    - name: Configure CMake
      run: ./configure.sh

    - name: Build
      run: ./build.sh