name: "Configure and build"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        run: docker build -t ghcr.io/ibois-epfl/ttool:latest ${{ github.workspace }}
      - name: Push
        run: docker push ghcr.io/ibois-epfl/ttool:latest

  configure-and-build:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ibois-epfl/ttool:latest
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        working-directory: /code
        run: cmake -B /code/build .
      - uses: actions/upload-artifact@v3
        with:
          name: configure-artifacts
          path: /code/build
          retention-days: 1
      - name: Build
        run: cmake --build /code/build
