name: docker-cmake-build
description: Buildind the app with a docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

runs:
  using: 'docker'
  image: 'Dockerfile'
